<?php
$refresh=NULL;
session_start();
include('config.php');
include('err-msgs.php');
include_once('../Functions/txtFunctions.sn.php');
include_once('../Functions/imgFunctions.ns.php');
include_once('../Functions/configFunctions.ns.php');
include_once('../Models1/general.ns.php');
include_once('../Models1/layout.ns.php');
include_once('../Models1/login/login.ns.php');
include_once('../Models1/logout/logout.ns.php');
include('../Models1/blog/index.php');
include('../Models1/inscription/index.php');
include('../Models1/members/index.php');
include('../Models1/photos/index.php');
include('../Models1/about/index.php');
include('../Models1/writings/index.php');
include('../Models1/home/index.php');
include('../Models1/contacts/index.php');
include('../Models1/newsletters/index.php');
$db=general\connection('localhost', '3306', 'mem_office', 'root', '');
?>